export const AUTH_LOGIN = 'AUTH_LOGIN'
export const AUTH_LOGOUT = 'AUTH_LOGOUT'
export const AUTH_LOGIN_WITH_TOKEN = 'AUTH_LOGIN_WITH_TOKEN'
export const AUTH_REGISTER = 'AUTH_REGISTER'
export const AUTH_EDIT = 'AUTH_EDIT'
export const AUTH_DELETE = 'AUTH_DELETE'
